export const ORDER_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    READY_FOR_PICKUP: "READY_FOR_PICKUP",
    SHIPPED: "SHIPPED",
    DELIVERED: "DELIVERED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
};

export const USER_ROLE = {
    USER: "USER",
    SUPER_ADMIN: "SUPER_ADMIN",
};

export const DOCUMENT_STATUS = {
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
};

export const DOCUMENT_TYPE = {
    SIA: "SIA",
    SIPA: "SIPA",
    KTP: "KTP",
    NPWP: "NPWP",
};
